services:

  postgresql:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "trades"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "trades", "-U", "admin" ]
      interval : 5s
      timeout : 5s
      retries : 5

  collector:
    image: otel/opentelemetry-collector-contrib
    restart: on-failure
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./src/collector/collector.yml:/collector.yml
    command: ["--config=/collector.yml"]
    environment:
      ELASTIC_APM_SERVER_ENDPOINT: ${ELASTIC_APM_SERVER_ENDPOINT}
      ELASTIC_APM_SERVER_SECRET: ${ELASTIC_APM_SERVER_SECRET}

  # recorder:
  #   build:
  #     context: ./src/recorder/
  #   restart: on-failure
  #   volumes:
  #     - ./logs:/logs
  #   command: ["-logfile=/logs/recorder.json"]
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     POSTGRES_HOST: "postgresql"
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_USER: "admin"
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
  #     OTEL_SERVICE_NAME: "recorder"
  #   depends_on:
  #     postgresql:
  #       condition: service_healthy
  #     collector:
  #       condition: service_started